/**
 * Clés alignées sur `app/lib/core/constants/permissions.dart` et `role_permissions` Supabase.
 */
export const P = {
  companyManage: "company.manage",
  storesCreate: "stores.create",
  storesRequestExtra: "stores.request_extra",
  storesApproveExtra: "stores.approve_extra",
  storesView: "stores.view",
  productsCreate: "products.create",
  productsUpdate: "products.update",
  productsDelete: "products.delete",
  productsView: "products.view",
  productsImport: "products.import",
  salesCreate: "sales.create",
  salesUpdate: "sales.update",
  salesCancel: "sales.cancel",
  salesRefund: "sales.refund",
  salesView: "sales.view",
  salesInvoiceA4: "sales.invoice_a4",
  salesInvoiceA4Table: "sales.invoice_a4_table",
  purchasesCreate: "purchases.create",
  purchasesView: "purchases.view",
  purchasesCancel: "purchases.cancel",
  purchasesUpdate: "purchases.update",
  purchasesDelete: "purchases.delete",
  stockAdjust: "stock.adjust",
  stockTransfer: "stock.transfer",
  stockView: "stock.view",
  /** Dépôt central : RPC + inventaire — rôle Magasinier (stock_manager) par défaut. */
  warehouseManage: "warehouse.manage",
  reportsViewGlobal: "reports.view_global",
  reportsViewStore: "reports.view_store",
  usersManage: "users.manage",
  settingsManage: "settings.manage",
  aiInsightsView: "ai.insights.view",
  cashOpenClose: "cash.open_close",
  cashView: "cash.view",
  auditView: "audit.view",
  dashboardView: "dashboard.view",
  customersView: "customers.view",
  customersManage: "customers.manage",
  /** Page Crédit / créances — owner par défaut ; accord explicite aux autres. */
  creditView: "credit.view",
  suppliersView: "suppliers.view",
  suppliersManage: "suppliers.manage",
  transfersCreate: "transfers.create",
  transfersApprove: "transfers.approve",
} as const;

/** Liste complète (équivalent `Permissions.all` Flutter) — super_admin. */
export const PERMISSIONS_ALL = Object.values(P);

/** Libellés FR pour la section gestion fine des droits (owner). */
export const PERMISSION_LABELS_FR: Record<string, string> = {
  [P.companyManage]: "Gerer l'entreprise",
  [P.storesCreate]: "Creer des boutiques",
  [P.storesRequestExtra]: "Demander des boutiques en plus",
  [P.storesApproveExtra]: "Approuver les demandes de boutiques",
  [P.storesView]: "Voir les boutiques",
  [P.productsCreate]: "Creer des produits",
  [P.productsUpdate]: "Modifier des produits",
  [P.productsDelete]: "Supprimer des produits",
  [P.productsView]: "Voir les produits",
  [P.productsImport]: "Importer des produits (CSV)",
  [P.salesCreate]: "Creer des ventes (caisse rapide)",
  [P.salesUpdate]: "Modifier des ventes completees",
  [P.salesCancel]: "Annuler des ventes",
  [P.salesRefund]: "Rembourser des ventes",
  [P.salesView]: "Voir l'historique des ventes",
  [P.salesInvoiceA4]: "Emettre des factures A4",
  [P.salesInvoiceA4Table]: "POS facture A4 (vue tableau)",
  [P.purchasesCreate]: "Creer des achats",
  [P.purchasesView]: "Voir les achats",
  [P.purchasesCancel]: "Annuler des achats",
  [P.purchasesUpdate]: "Modifier des achats (brouillons)",
  [P.purchasesDelete]: "Supprimer des achats (brouillons)",
  [P.stockAdjust]: "Ajuster le stock",
  [P.stockTransfer]: "Transferer le stock",
  [P.stockView]: "Voir le stock / inventaire",
  [P.warehouseManage]: "Gerer le depot magasin (complet)",
  [P.reportsViewGlobal]: "Voir les rapports (global)",
  [P.reportsViewStore]: "Voir les rapports (boutique)",
  [P.usersManage]: "Gerer les utilisateurs",
  [P.settingsManage]: "Gerer les parametres",
  [P.aiInsightsView]: "Voir les insights IA",
  [P.cashOpenClose]: "Ouvrir / fermer la caisse",
  [P.cashView]: "Voir la caisse / mouvements",
  [P.auditView]: "Voir l'audit",
  [P.dashboardView]: "Voir le tableau de bord",
  [P.customersView]: "Voir les clients",
  [P.customersManage]: "Gerer les clients",
  [P.creditView]: "Voir la page Credit (creances clients)",
  [P.suppliersView]: "Voir les fournisseurs",
  [P.suppliersManage]: "Gerer les fournisseurs",
  [P.transfersCreate]: "Creer / gerer les transferts",
  [P.transfersApprove]: "Approuver les transferts",
};
